version: '3.8'
services:
  pg-db:
    build:
      context: .
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - my_pgdata:/var/lib/postgresql/data

volumes:
  my_pgdata:
